config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"
  resources :recipes, only: [:index, :new, :create, :show, :edit, :update,:destroy]
  resources :cuisines, only: [:new, :create, :show]
  resources :food_types, only: [:new, :create, :show]
  resources :users, only: [:new, :create, :show]
  resources :favorites, only: [:create, :destroy]
  get '/search', to: 'recipes#search'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
  # validates :name, uniqueness: { case_sensitive: false },  presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/food_type.rb
class FoodType < ApplicationRecord
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, :cuisine_id, :food_type_id, :ingredients,
            :prep_steps, :user_id, presence: true
  belongs_to :cuisine
  belongs_to :food_type
  belongs_to :user
  has_many :favorites
  enum difficulty: { easy: 1, medium: 2, hard: 3 }
  mount_uploader :picture, PictureUploader

  def favorite_by?(user)
    favorites.where(user: user).any?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :recipes
  has_many :favorites
  validates :mail, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    redirect_to login_path unless current_user
  end
  
  helper_method :current_user
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def new
    @cuisine = Cuisine.new
    collections_all
  end

  def create
    @cuisine = Cuisine.new cuisine_params
    @cuisine.save
    collections_all
    redirect_to @cuisine
  end

  def show
    @cuisine = Cuisine.find params[:id]
    collections_all
  end

  private

  def cuisine_params
    params.require(:cuisine).permit(:name)
  end

  def collections_all
    @cuisines = Cuisine.all
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    collections_all
    favorite = Favorite.create(favorite_params)
    redirect_back(fallback_location: new_user_path)
  end

  def destroy
    collections_all
    favorite = Favorite.find_by user_id: params[:user_id], recipe_id: params[:recipe_id]
    favorite.destroy
    redirect_back(fallback_location: new_user_path)
  end

  private

  def favorite_params
    { user_id: params[:user_id], recipe_id: params[:recipe_id] }
  end

  def collections_all
    @recipes = Recipe.all
    @users = User.all
  end
end

app/controllers/food_types_controller.rb
class FoodTypesController < ApplicationController
  def new
    collections_all
    @food_type = FoodType.new
  end

  def create
    collections_all
    @food_type = FoodType.new(food_type_params)
    @food_type.save
    redirect_to @food_type
  end

  def show
    collections_all
    @food_type = FoodType.find params[:id]
  end

  private

  def food_type_params
    params.require(:food_type).permit(:name)
  end

  def collections_all
    @food_types = FoodType.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    @recipes = Recipe.last(5)
    @difficulties = Recipe.difficulties
    @cuisines = Cuisine.all
    @food_types = FoodType.all
  end

  def new
    @recipe = Recipe.new
    collections_all
  end

  def create
    collections_all
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to @recipe
      flash[:notice] = 'Receita criada com sucesso!'
    else
      flash.now[:notice] = 'Sua receita nao pode ser criada.'
      render :new
    end
  end

  def show
    @recipe = Recipe.find params[:id]
  end

  def search
    search = params[:search]
    @recipes = Recipe.all.select do |recipe|
      recipe.name.downcase.include?(search.downcase)
    end
  end

  def edit
    @recipe = Recipe.find params[:id]
    collections_all
    if @recipe.user == current_user
      render :edit
    else
      flash[:notice] = 'Você não pode editar essa receita.'
      redirect_to root_url
    end
  end

  def update
    collections_all
    @recipe = Recipe.find params[:id]
    @recipe.update recipe_params if @recipe.user == current_user
    if @recipe.update recipe_params
      redirect_to @recipe
      flash[:notice] = 'Receita editada com sucesso!'
    else
      flash.now[:notice] = 'Não foi possível editar a receita.'
      render :edit
    end
  end

  def destroy
    recipe = Recipe.find params[:id]
    if recipe.user == current_user
      recipe.destroy
      redirect_to user_path(recipe.user)
      flash[:notice] = 'Receita excluida com sucesso!'
    else
      flash.now[:notice] = 'Você não pode excluir essa receita.'
      render :index
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :food_type_id, :cuisine_id,
                                   :serves, :prep_time, :difficulty,
                                   :ingredients, :prep_steps, :picture,
                                   :user_id)
  end

  def collections_all
    @recipes = Recipe.all
    @difficulties = Recipe.difficulties
    @cuisines = Cuisine.all
    @food_types = FoodType.all
    @users = User.all
    @favorite = Favorite.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(mail: session_params[:mail].downcase)
    if authentic?
      session[:user_id] = @user.id
      flash[:notice] = "Bem-vindo(a) de volta, #{@user.name}!"
      redirect_to root_path
    else
      flash.now[:notice] = 'E-mail ou senha inválido'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
    flash[:notice] = 'Log out com sucesso!'
  end

  private

  def session_params
    params.require(:session).permit(:mail, :password)
  end

  def authentic?
    password = session_params[:password]
    @user && @user.authenticate(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    collections_all
  end

  def create
    @user = User.new(user_params)
    @user.save
    if @user.save
      redirect_to login_path
      flash[:notice] = 'Usuário criado com sucesso!'
    else
      flash.now[:notice] = 'Não foi possível criar o usuário'
      render :new
    end
  end

  def show
    collections_all
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :mail, :city, :password,
                                 :password_confirmation)
  end

  def collections_all
    @recipes = Recipe.all
    @cuisines = Cuisine.all
    @food_types = FoodType.all
    @favorite = Favorite.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/_form.html.erb
<section id="cuisine">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @cuisine do |f| %>
        <div class="form-group">
          <%= f.label :name, "Nome" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <%= f.submit text_submit, class: "btn btn-default" %>
      <% end %>
</section>

<%= button_to "Voltar", root_path, method: :get, class: "btn btn-default"  %>

app/views/cuisines/new.html.erb
<h1>Nova cozinha</h1>
<%= render partial: "form", locals: { text_submit: "Criar Cozinha" } %>

app/views/cuisines/show.html.erb
<section id="cuisine">
  <h1><%= @cuisine.name %></h1>
</section>

<div class="col-md-4">
  <section id="recipes">
    <% @cuisine.recipes.each do |recipe| %>
      <div class="thumbnail">
        <%= image_tag recipe.picture.url unless recipe.picture.blank? %>
        <div class="caption">
          <h2 class="text-center"><%= link_to recipe.name, recipe_path(recipe) %></h2>
          <dl class="dl-horizontal">
            <dt>Tipo de comida</dt>
            <dd><%= recipe.food_type.name %></dd>
            <dt>Serve</dt>
            <dd><%= recipe.serves %> pessoa(s)</dd>
            <dt>Tempo de preparo</dt>
            <dd><%= recipe.prep_time %> minuto(s)</dd>
            <dt>Dificuldade</dt>
            <dd><%= recipe.difficulty.humanize %></dd>
          </dl>
          <% if recipe.user == current_user %>
            <%= button_to "Editar", edit_recipe_path(recipe), method: :get, class: "btn btn-default btn-xs" %>
            <%= button_to "Excluir", @recipe_id, method: :delete, class: "btn btn-default btn-xs" %>
          <% end %>
        </div>
      </div>
    <% end%>
  </section>
</div>

<p><%= button_to "Voltar", root_path, method: :get, class: "btn btn-default"%></p>

app/views/food_types/_form.html.erb
<section id="food_type">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @food_type do |f| %>
        <div class="form-group">
          <%= f.label :name, "Nome" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <%= f.submit text_submit, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</section>

<%= button_to "Voltar", root_path, method: :get, class: "btn btn-default" %>

app/views/food_types/new.html.erb
<h1>Novo tipo de comida</h1>
<%= render partial: "form", locals: { text_submit: "Criar Tipo de Comida"} %>

app/views/food_types/show.html.erb
<section id="food_type">
  <h1><%= @food_type.name %></h1>
</section>

<div class="col-md-4">
  <section id="recipes">
    <% @food_type.recipes.each do |recipe| %>
    <div class="thumbnail">
      <%= image_tag recipe.picture.url unless recipe.picture.blank? %>
      <div class="caption">
        <h2 class="text-center"><%= link_to recipe.name, recipe_path(recipe) %></h2>
        <dl class="dl-horizontal">
          <dt>Cozinha</dt>
          <dd><%= recipe.cuisine.name %></dd>
          <dt>Serve</dt>
          <dd><%= recipe.serves %> pessoa(s)</dd>
          <dt>Tempo de preparo</dt>
          <dd><%= recipe.prep_time %> minuto(s)</dd>
          <dt>Dificuldade</dt>
          <dd><%= recipe.difficulty.humanize %></dd>
        </dl>
        <% if recipe.user == current_user %>
          <%= button_to "Editar", edit_recipe_path(recipe), method: :get, class: "btn btn-default btn-xs" %>
          <%= button_to "Excluir", @recipe_id, method: :delete, class: "btn btn-default btn-xs" %>
        <% end %>
      </div>
    </div>
    <% end%>
  </section>
</div>

<%= button_to "Voltar", root_path, method: :get, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialRecipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-brand"><%= link_to "Social Recipes", root_path %></div>

          <div class="row">

            <section id="search">
              <div class="col-md-4">
                <form class="navbar-form navbar-left">
                  <%= form_tag("/search", method: "get") do %>
                    <%= label_tag(:search, "Buscar Receita") %>
                    <%= text_field_tag(:search) %>
                    <%= submit_tag("Buscar") %>
                  <% end %>
                </form>
              </div>
            </section>

            <section id="authentication">
                <div class="col-md-1 col-md-offset-2">
                  <%= link_to "Criar receita", new_recipe_path, method: :get, class: "btn btn-default navbar-btn" %>
                </div>
                <% if current_user %>
                  <div class="col-md-2">
                    <%=link_to "Meu perfil", user_path(current_user), method: :get, class: "btn btn-default navbar-btn" %>
                  </div>
                  <div class="col-md-1">
                    <%=link_to "Sair", logout_path, method: "delete", class: "btn btn-default navbar-btn" %>
                  </div>
                <% else %>
                  <div class="col-md-1">
                    <%= link_to "Criar usuário", new_user_path, method: "get", class: "btn btn-default navbar-btn" %>
                  </div>
                  <div class="col-md-1">
                    <%= link_to "Entrar", login_path, method: "get", class: "btn btn-default navbar-btn" %>
                  </div>
                <% end %>
            </section>

          </div>
        </div>
     </nav>
    </header>

    <main>
    <div class="container">
      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>

      <%= yield %>
    </div>
    </main>
  </body>
</html>

app/views/recipes/_favorite.html.erb
<% if current_user %>
  <% if @recipe.favorite_by?(current_user) %>
    <strong>Favorita!</strong>
    <%= button_to "Desfavoritar", favorite_path(recipe_id: @recipe.id, user_id: current_user.id), method: :delete, class: "btn btn-default btn-xs" %>
  <% else %>
    <strong><%= button_to "Favoritar", favorites_path(recipe_id: @recipe.id, user_id: current_user), method: :post, class: "btn btn-default btn-xs" %></strong>
  <% end %>
<% end %>

app/views/recipes/_form.html.erb
<section id="recipes">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @recipe, class: "form-horizontal" do |f| %>
        <div class="form-group">
          <%= f.label :name, 'Nome' %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :serves, 'Quantas pessoas serve' %>
          <%= f.text_field :serves, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :prep_time, 'Tempo de preparo (em minutos)' %>
          <%= f.text_field :prep_time, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :ingredients, 'Ingredientes' %>
          <%= f.text_area :ingredients, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :prep_steps, 'Passo a passo' %>
          <%= f.text_area :prep_steps, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :cuisine_id, 'Cozinha' %>
          <%= f.collection_select(:cuisine_id, @cuisines, :id, :name)%>
        </div>
        <div class="form-group">
          <%= f.label :food_type_id, 'Tipo de comida' %>
          <%= f.collection_select(:food_type_id, @food_types, :id, :name) %>
        </div>
        <div class="form-group">
          <%= f.label :difficulty, 'Nível de dificuldade' %>
          <%= f.select :difficulty,
          options_for_select(@difficulties.collect { |s| [s[0].humanize, s[0]] },
          selected: @recipe.difficulty) %>
        </div>
        <div class="input-group">
          <%= f.label :picture, "Foto" %>
          <%= f.file_field :picture %>
        </div>
        <br>
        <%= f.submit text_submit, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</section>

<%= button_to 'Voltar', root_path, method: 'get', class: "btn btn-default" %>

app/views/recipes/edit.html.erb
<h1>Editar receita</h1>
<%= render partial: "form", locals: { text_submit: 'Editar Receita' } %>

app/views/recipes/index.html.erb
<div class="col-md-4 text-left">
  <section id="cuisines">
    <h1>Cozinhas</h1>
    <ul class="list-group">
      <% @cuisines.each do |cuisine| %>
        <h3><%= link_to cuisine.name, cuisine_path(cuisine), class: "list-group-item" %></h3>
      <% end %>
    </ul>
  </section>

  <section id="food_types">
    <h1>Tipos de comida</h1>
    <ul class="list-group">
      <% @food_types.each do |food_type| %>
        <h3><%= link_to food_type.name, food_type_path(food_type) , class: "list-group-item"%></h3>
      <% end %>
    <ul>
  </section>
</div>

<div class="col-md-4">
  <section id="recipes">
    <h1>Receitas</h1>
    <% @recipes.each do |recipe| %>
      <div class="thumbnail">
        <%= image_tag recipe.picture.url, width: 200, height: 200 unless recipe.picture.blank? %>
        <div class="caption">
          <h2 class="text-center"><%= link_to recipe.name, recipe_path(recipe) %></h2>
          <section id="favorite">
            <% if current_user %>
              <% if recipe.favorite_by?(current_user) %>
                <strong>Favorita!</strong>
              <% else %>
                <strong><%= button_to "Favoritar", favorites_path(recipe_id: recipe.id, user_id: current_user), method: :post, class: "btn btn-default btn-xs" %></strong>
              <% end %>
            <% end %>
          </section>
          <dl class="dl-horizontal">
            <dt>Cozinha</dt>
            <dd><%= recipe.cuisine.name%></dd>
            <dt>Tipo de comida</dt>
            <dd><%= recipe.food_type.name %></dd>
            <dt>Serve</dt>
            <dd><%= recipe.serves %> pessoa(s)</dd>
            <dt>Tempo de preparo</dt>
            <dd><%= recipe.prep_time %> minuto(s)</dd>
            <dt>Dificuldade</dt>
            <dd><%= recipe.difficulty.humanize %></dd>
          </dl>

          <section id="management">
            <% if recipe.user == current_user %>
              <%= link_to "Editar", edit_recipe_path(recipe), method: :get, class: "btn btn-default btn-xs" %>
              <%= link_to "Excluir", @recipe_id, method: :delete, class: "btn btn-default btn-xs" %>
            <% end %>
          </section>
        </div>
      </div>
    <% end %>
  </section>
</div>

app/views/recipes/new.html.erb
<h1>Nova receita</h1>
<%= render partial: "form", locals: { text_submit: 'Criar Receita' } %>

app/views/recipes/search.html.erb
<section id="recipes">
  <% if @recipes %>
    <% @recipes.each do |recipe| %>
      <div class="recipe">
        <%= link_to recipe.name, recipe_path(recipe)%>
      </div>
    <% end %>
  <% else %>
    <h2>Nenhuma receita encontrada =/</h2>
  <% end %>
</section>

<%= button_to "Voltar", root_path, method: :get, class: "btn btn-default" %>

app/views/recipes/show.html.erb
<section id="recipe">
  <div class="image">
    <%= image_tag @recipe.picture.url unless @recipe.picture.blank? %>
  </div>
  <div class="dl-horizontal">
    <h1><%= @recipe.name %></h1>
    <%= render partial: "favorite" %>
    <dl>
      <dt>Tipo de comida</dt>
      <dd><%= @recipe.food_type.name %></dd>
      <dt>Cozinha</dt>
      <dd><%= @recipe.cuisine.name %></dd>
      <dt>Serve</dt>
      <dd><%= @recipe.serves %> pessoa(s)</dd>
      <dt>Tempo de preparo</dt>
      <dd><%= @recipe.prep_time %> minuto(s)</dd>
      <dt>Nível de dificuldade</dt>
      <dd><%= @recipe.difficulty.humanize %></dd>
      <dt> Ingredientes</dt>
      <dd><%= @recipe.ingredients %></dd>
      <dt>Passo a passo</dt>
      <dd><%= @recipe.prep_steps %></dd>
      <dt>Criado por</dt>
      <dd><%= @recipe.user.name %></dd>
    </dl>
    <% if @recipe.user == current_user %>
      <%= link_to "Editar", edit_recipe_path(@recipe), method: :get, class: "btn btn-default" %>
      <%= link_to "Excluir", @recipe_id, method: :delete, class: "btn btn-default" %>
    <% end %>
  </div>
  <p><%= link_to "Voltar", root_path, method: :get, class: "btn btn-default btn-xs" %></p>
</section>

app/views/users/new.html.erb
<section id='user'>
  <h1>Criar usuário</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "Nome" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :mail, "E-mail" %>
          <%= f.email_field :mail, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password, "Senha" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "Confirmar senha" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <p><%= f.submit "Criar Usuário", class: "btn btn-default" %></p>
      <% end %>
</section>
 <p><%= link_to "Voltar", root_path, method: :get, class: "btn btn-default" %></p>

app/views/users/show.html.erb
<section id="user">
  <address>
    <p><strong><%= @user.name %></strong></p>
    <p><%= @user.mail %></p>
    <p><a href="mailto:#"><%= @user.city %></a></p>
  </address>
</section>

<div class="col-md-6">
  <section id="recipes">
    <h1>Recipes</h1>
    <p><%= link_to "Criar receita", new_recipe_path, class: 'btn btn-default' %></p>

    <% @user.recipes.each do |recipe| %>
      <strong><%= link_to recipe.name, recipe_path(recipe) %></strong>
      <dl class="dl-horizontal">
        <dt>Tipo de comida</dt>
        <dd><%= recipe.food_type.name %></dd>
        <dt>Cozinha</dt>
        <dd><%= recipe.cuisine.name %></dd>
      </dl>
    <% end %>
  </section>
</div>

<div class="col-md-6">
  <section id="favorites">
    <h1>Minhas favoritas</h1>
    <% @user.favorites.each do |favorite| %>
      <% recipe = Recipe.find(favorite[:recipe_id]) %>
      <strong><%= link_to recipe.name, recipe_path(recipe) %></strong>
      <dl class="dl-horizontal">
        <dt>Tipo de comida</dt>
        <dd><%= recipe.food_type.name %></dd>
        <dt>Cozinha</dt>
        <dd><%= recipe.cuisine.name %></dd>
      </dl>
    <% end %>
  </section>
</div>
<p><%= link_to "Voltar", root_path, method: :get, class: 'btn btn-default' %>